---
title: "ECB Lean Mass Phenotype"
editor_options: null
chunk_output_type: inline
output: html_document

---
### Goal: Rear UZ and BE at 23C at 16:8 and 12:12 L:D regimens (UZ12, UZ16, BE12, BE16). Track lean mass changes during the 5th instar, the wandering stage, and during diapause. 

##Call Data
````{r}
library(readxl)
library(ggplot2)
library(nlme)
library(lme4)
library(lmerTest)
library(ez)
library(lsr)
library(dplyr)
library(tidyr)
library(MASS)
library(doBy)
library(plyr)


##PC
data=read_excel("/Users/jbrown/Documents/GitHub/Lipid_Quantification/Data/Extraction Samples JLM.xlsx",sheet = "CONTSAMPdf")


##MAC
## reading in the data and looking at its structure
#setwd("/Users/JamesB/Google Drive/Graduate School/Self_JamesTBrown/GitHub/Lipid_Quantification/Scripts_Analysis")
#data=read_excel("/Users/JamesB/Google Drive/Graduate School/Self_JamesTBrown/GitHub/Lipid_Quantification/Data/Extraction Samples JLM.xlsx", sheet = "CONTSAMPdf")

data=subset(data,treat!="NA")
data=subset(data,cohort!="20180131")
data=subset(data,cohort!="20180206")
data=subset(data,sample_day!="W14")
data=subset(data,sample_day!="W19")
data=subset(data,sample_day!="W29")


##This code breaks apart the data in the column "treat" into "strain" and "photoperiod"
data$sample_id<-as.factor(as.character(data$sample_id))
data$strain<-substr(data$treat,1,2)
data$photoperiod<-as.numeric(substr(data$treat,3,4))
data$strain<-as.factor(as.character(data$strain))
data$photoperiod<-as.factor(as.character(data$photoperiod))
data$treat<-as.factor(as.character(data$treat))
data$sample_day<-factor(data$sample_day, levels=c("1" , "3" , "7" , "W" , "pW1" , "pW5" , "pW10" , "W14" ,"W15" , "pW18" , "W19" , "W20" , "W29" , "W30" , "pW38" , "W45"))
data$cohort<-as.factor(as.character(data$cohort))

#Reducing df
data1=data[1:626, c("sample_day","rep", "treat","sample_id","5th_date","cohort", "wet_mass","dry_mass","lean_mass","lipid_mass","strain","photoperiod")]

#converting wide to long. This code puts all the observations into one column with the label of your choice (measurements used below)
dataT=gather(data,traits,measurement,wet_mass:lipid_mass)
#str(dataT) #shows the structure of the data
#str(data)
````

##Traits Plots
````{r}
#Larva Trait Plot
dataTr=dataT
dataTr=subset(dataTr,measurement!="NA")
dataTr=subset(dataTr,photoperiod!="NA")
count(dataTr$treat)
dataTr=subset(dataTr,sample_day=="1"| sample_day=="W"| sample_day=="W15"| sample_day=="W20" | sample_day=="W30")
dataTr=subset(dataTr,measurement>=0.0001)
dataTr=subset(dataTr,measurement<=0.1100)
ggplot(data=dataTr,aes(x=sample_day,y=measurement,fill=traits))+
  geom_boxplot()+
  facet_wrap(~treat)+
  theme_classic()+
  ggtitle("Larvae Traits")+
  ylab("Traits")+xlab("Sample Day")

#Larva lean Mass Plot
datal=data1
datal=subset(datal,lean_mass>=0.0001)
datal=subset(datal,lean_mass<=0.1000)
count(datal$treat)
datal=subset(datal,sample_day=="1"| sample_day=="W"| sample_day=="W15"| sample_day=="W20" | sample_day=="W30")
```

##Lean Mass Comparison Between Treatments
```{r}
#Larva Lean Mass Comparison Between Treatments
dataL=data1
dataL=subset(dataL,lean_mass>=0)
#dataL=subset(dataL,lean_mass<=0.1000)
count(dataL$treat)
dataL=subset(dataL,sample_day=="1"| sample_day=="W")
ggplot(data=dataL,aes(x=sample_day,y=lean_mass,group=photoperiod,color=photoperiod))+
  stat_summary(aes(y = lean_mass), fun.y=mean, geom="line")+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 178 : BE 164 larvae)")+
  ylab("lean Mass")+xlab("Sample Day")




### Is there a significant difference in lean mass accumulation between treatments in preparation for diapause?
#### These Data include Day 1 larvae and Day W larvae from both treatments.

######################
# Larva Lean Mass    #
# Between Strains ####
# Between Treatments #
###### Day 1 #########


dataL1=subset(data,sample_day=="1")
dataL1=subset(dataL1,lean_mass>="0")
dataL1=subset(dataL1,lean_mass<="0.07")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Photoperiod Does NOT SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedL1=lmer(lean_mass ~ photoperiod + (1|rep) ,data=dataL1, REML = TRUE)
summary(mixedL1)
plot(mixedL1)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodL1=lmer(lean_mass ~ (1|rep),data=dataL1, REML = TRUE)
summary(submodL1)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataL1$stdresL1<-as.vector(scale(resid(submodL1)))

ggplot(data=dataL1,aes(x=sample_day,y=lean_mass,color=photoperiod))+
  stat_summary(aes(y = lean_mass), fun.y=mean)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass")+
  ylab("lean Mass")+xlab("Sample Day 1")



######################
# Larva Lean Mass    #
# Between Strains ####
# Between Treatments #
###### Day W #########

##Mixed model with 'rep' as a random factor

dataLW=subset(data,sample_day=="W")
dataLW=subset(dataLW,lean_mass>="0")
dataLW=subset(dataLW,lean_mass<="0.07")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Photoperiod does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLW=lmer(lean_mass ~ photoperiod + (1|rep) ,data=dataLW, REML = TRUE)
summary(mixedLW)
plot(mixedLW)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLW=lmer(lean_mass ~ (1|rep),data=dataLW, REML = TRUE)
summary(submodLW)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLW$stdresLW<-as.vector(scale(resid(submodLW)))

ggplot(data=dataLW,aes(x=sample_day,y=lean_mass,color=photoperiod))+
  stat_summary(aes(y = lean_mass), fun.y=mean)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass")+
  ylab("lean Mass")+xlab("Sample Day W")
```

##Lean Mass Comparison Within Diapause Treatment
```{r}
######################
#Larva lean Mass Plot#
# Within  Treatments #
######################

### Diapause###
dataLeD=data1
dataLeD=subset(dataLeD,photoperiod==12)
dataLeD=subset(dataLeD,lean_mass>=0)
#dataLeD=subset(dataLeD,lean_mass<=0.1000)
count(dataLeD$treat)
dataLeD=subset(dataLeD,sample_day=="1"| sample_day=="W"| sample_day=="W15"| sample_day=="W20" | sample_day=="W30")

ggplot(data=dataLeD,aes(x=sample_day,y=lean_mass,group=treat,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("Diapause: Between Strain Comparison of Larvae lean Mass (UZ 117 : BE 107 larvae)")+
  ylab("lean Mass")+xlab("Sample Day")
  
######################
# Larva Lean Mass    #
# Within  Treatments #
###### Day 1 #########

##Mixed model with 'rep' as a random factor

dataLeD1=subset(data1,photoperiod==12)
dataLeD1=subset(dataLeD1,lean_mass>=0)
dataLeD1=subset(dataLeD1,sample_day=="1")
count(dataLeD1$treat)

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Strain does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLeD1=lmer(lean_mass ~  strain + (1|rep),data=dataLeD1, REML = TRUE)
summary(mixedLeD1)
plot(mixedLeD1)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLeD1=lmer(lean_mass ~ (1|rep),data=dataLeD1, REML = TRUE)
summary(submodLeD1)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLeD1$stdresLeD1<-as.vector(scale(resid(submodLeD1)))

ggplot(data=dataLeD1,aes(x=sample_day,y=lean_mass,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 25 : BE 17 larvae)")+
  ylab("lean Mass")+xlab("Sample Day 1")

######################
# Larva Lean Mass    #
# Between Strains ####
# Within  Treatments #
###### Day W #########

##Mixed model with 'rep' as a random factor

dataLeDW=subset(data1,photoperiod==12)
dataLeDW=subset(dataLeDW,lean_mass>=0)
dataLeDW=subset(dataLeDW,sample_day=="W")


#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Strain does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLeDW=lmer(lean_mass ~  strain + (1|rep),data=dataLeDW, REML = TRUE)
summary(mixedLeDW)
plot(mixedLeDW)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLeDW=lmer(lean_mass ~ (1|rep),data=dataLeDW, REML = TRUE)
summary(submodLeDW)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLeDW$stdresLeDW<-as.vector(scale(resid(submodLeDW)))

ggplot(data=dataLeDW,aes(x=sample_day,y=lean_mass,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 34 : BE 43 larvae)")+
  ylab("lean Mass")+xlab("Sample Day W")


######################
# Larva Lean Mass    #
# Between Strains ####
# Within  Treatments #
###### Day W15 #######

##Mixed model with 'rep' as a random factor

dataLeDW15=subset(data1,sample_day=="W15")
dataLeDW15=subset(dataLeDW15,lean_mass>="0")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Photoperiod does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLeDW15=lmer(lean_mass ~ strain + (1|rep) ,data=dataLeDW15, REML = TRUE)
summary(mixedLeDW15)
plot(mixedLeDW15)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLeDW15=lmer(lean_mass ~ (1|rep),data=dataLeDW15, REML = TRUE)
summary(submodLeDW15)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLeDW15$stdresLeDW15<-as.vector(scale(resid(submodLeDW15)))

ggplot(data=dataLeDW15,aes(x=sample_day,y=lean_mass,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 19 : BE 37 larvae)")+
  ylab("lean Mass")+xlab("Sample Day W15")

######################
# Larva Lean Mass    #
# Between Strains ####
# Within  Treatments #
###### Day w20 #######

##Mixed model with 'rep' as a random factor

dataLeDW20=subset(data1,sample_day=="W20")
dataLeDW20=subset(dataLeDW20,lean_mass>="0")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Photoperiod does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLeDW20=lmer(lean_mass ~ strain + (1|rep) ,data=dataLeDW20, REML = TRUE)
summary(mixedLeDW20)
plot(mixedLeDW20)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLeDW20=lmer(lean_mass ~ (1|rep),data=dataLeDW20, REML = TRUE)
summary(submodLeDW20)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLeDW20$stdresLeDW20<-as.vector(scale(resid(submodLeDW20)))

ggplot(data=dataLeDW20,aes(x=sample_day,y=lean_mass,color=treat))+
  stat_summary(aes(y = lean_mass,group=treat), fun.y=mean, geom="line")+
  stat_summary(fun.y=median, fun.ymin=function(x) median(x) - sd(x), 
               fun.ymax=function(x) median(x) + sd(x), geom="errorbar", width=0.1) +
  facet_wrap(~photoperiod)+
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 20 : BE 6 larvae)")+
  ylab("lean Mass")+xlab("Sample Day W20")


######################
# Larva Lean Mass    #
# Between Strains ####
# Within  Treatments #
###### Day w30 #######

##Mixed model with 'rep' as a random factor

dataLeDW30=subset(data1,sample_day=="W30")
dataLeDW30=subset(dataLeDW30,lean_mass>="0")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Photoperiod does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLeDW30=lmer(lean_mass ~ strain + (1|rep) ,data=dataLeDW30, REML = TRUE)
summary(mixedLeDW30)
plot(mixedLeDW30)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLeDW30=lmer(lean_mass ~ (1|rep),data=dataLeDW30, REML = TRUE)
summary(submodLeDW30)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLeDW30$stdresLeDW30<-as.vector(scale(resid(submodLeDW30)))

ggplot(data=dataLeDW30,aes(x=sample_day,y=lean_mass,color=treat))+
  stat_summary(aes(y = lean_mass,group=treat), fun.y=mean, geom="line")+
  stat_summary(fun.y=median, fun.ymin=function(x) median(x) - sd(x), 
               fun.ymax=function(x) median(x) + sd(x), geom="errorbar", width=0.1) +
  facet_wrap(~photoperiod)+
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 19 : BE 4 larvae)")+
  ylab("lean Mass")+xlab("Sample Day W30")
```

##Lean Mass Comparison Within Non Diapause Treatment
```{r}
######################
#Larva lean Mass Plot#
# Within   Treatment #
######################

### Non Diapause###
dataLeND=data1
dataLeND=subset(dataLeND,photoperiod==16)
dataLeND=subset(dataLeND,lean_mass>=0)
#dataLeND=subset(dataLeND,lean_mass<=0.1000)
count(dataLeND$treat)
dataLeND=subset(dataLeND,sample_day=="1"| sample_day=="W")

ggplot(data=dataLeND,aes(x=sample_day,y=lean_mass,group=treat,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("Non Diapause: Between Strain Comparison of Larvae lean Mass (UZ 117 : BE 107 larvae)")+
  ylab("lean Mass")+xlab("Sample Day")
  
######################
# Larva Lean Mass    #
# Within  Treatments #
###### Day 1 #########

##Mixed model with 'rep' as a random factor

dataLeND1=subset(data1,photoperiod==12)
dataLeND1=subset(dataLeND1,lean_mass>=0)
dataLeND1=subset(dataLeND1,sample_day=="1")
count(dataLeND1$treat)

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Strain does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLeND1=lmer(lean_mass ~  strain + (1|rep),data=dataLeND1, REML = TRUE)
summary(mixedLeND1)
plot(mixedLeND1)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLeND1=lmer(lean_mass ~ (1|rep),data=dataLeND1, REML = TRUE)
summary(submodLeND1)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLeND1$stdresLeND1<-as.vector(scale(resid(submodLeND1)))

ggplot(data=dataLeND1,aes(x=sample_day,y=lean_mass,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 25 : BE 17 larvae)")+
  ylab("lean Mass")+xlab("Sample Day 1")

######################
# Larva Lean Mass    #
# Between Strains ####
# Within  Treatments #
###### Day W #########

##Mixed model with 'rep' as a random factor

dataLeNDW=subset(data1,photoperiod==12)
dataLeNDW=subset(dataLeNDW,lean_mass>=0)
dataLeNDW=subset(dataLeNDW,sample_day=="W")


#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
## Strain does SIGNIFICANTLY effect lean mass accumulation between larvae reared in long day vs short day conditions
mixedLeNDW=lmer(lean_mass ~  strain + (1|rep),data=dataLeNDW, REML = TRUE)
summary(mixedLeNDW)
plot(mixedLeNDW)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lean mass
submodLeNDW=lmer(lean_mass ~ (1|rep),data=dataLeNDW, REML = TRUE)
summary(submodLeNDW)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataLeNDW$stdresLeNDW<-as.vector(scale(resid(submodLeNDW)))

ggplot(data=dataLeNDW,aes(x=sample_day,y=lean_mass,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("Treatment Comparison of Larvae lean Mass (UZ 34 : BE 43 larvae)")+
  ylab("lean Mass")+xlab("Sample Day W")
```

```{r}
######################
# Larva lean Mass    #
# Within Strain      #
# Between Treatments #
######################

### BE ###
dataLeBE=data1
dataLeBE=subset(dataLeBE,strain!="UZ")
dataLeBE=subset(dataLeBE,lean_mass>=0.0001)
#dataLeBE=subset(dataLeBE,lean_mass<=0.1000)
count(dataLeBE$treat)
dataLeBE=subset(dataLeBE,sample_day=="1"| sample_day=="W")

ggplot(data=dataLeBE,aes(x=sample_day,y=lean_mass,group=treat,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("BE: Within Strain Comparison of Larvae lean Mass")+
  ylab("lean Mass")+xlab("Sample Day")
  
dataLeBE=data1
dataLeBE=subset(dataLeBE,strain!="UZ")
dataLeBE=subset(dataLeBE,lean_mass>=0.0001)
#dataLeBE=subset(dataLeBE,lean_mass<=0.1000)
dataLeBE=subset(dataLeBE,sample_day=="1"| sample_day=="W")

ggplot(data=dataLeBE,aes(x=sample_day,y=lean_mass,group=treat,color=treat))+
  stat_summary(fun.y=mean, geom="line")+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  geom_smooth(method=lm,color="black",se=TRUE)+
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("BE: Within Strain Comparison of Larvae lean Mass")+
    ylab("lean Mass")+
    xlab("Sample Day")

### UZ ###
dataLeUZ=data1
dataLeUZ=subset(dataLeUZ,photoperiod!="12")
dataLeUZ=subset(dataLeUZ,lean_mass>=0.0001)
#dataLeUZ=subset(dataLeUZ,lean_mass<=0.1000)
count(dataLeUZ$treat)
dataLeUZ=subset(dataLeUZ,sample_day=="1"| sample_day=="W")

ggplot(data=dataLeUZ,aes(x=sample_day,y=lean_mass,group=treat,color=treat))+
  stat_summary(fun.y=mean, geom="line",shape=18)+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("UZ: Within Strain Comparison of Larvae lean Mass")+
  ylab("lean Mass")+xlab("Sample Day")
  
dataLeUZ=data1
dataLeUZ=subset(dataLeUZ,photoperiod!="12")
dataLeUZ=subset(dataLeUZ,lean_mass>=0.0001)
#dataLeUZ=subset(dataLeUZ,lean_mass<=0.1000)
dataLeUZ=subset(dataLeUZ,sample_day=="1"| sample_day=="W")

ggplot(data=dataLeUZ,aes(x=sample_day,y=lean_mass,group=treat,color=treat))+
  stat_summary(fun.y=mean, geom="line")+
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.05) +
  geom_smooth(method=lm,color="black",se=TRUE)+
  scale_color_manual(values=c(UZ12="purple",UZ16="purple",BE12="orange",BE16="orange"))+
  theme_classic()+
  ggtitle("UZ: Within Strain Comparison of Larvae lean Mass")+
    ylab("lean Mass")+
    xlab("Sample Day")
```






```{r}

## Is there a difference in lipid accumulation between strains, within the 16:8 LD treatment? Models and plots only include data from the 16:8 LD treatment.

##########NDia############
##Lipid Mass btw  Strain##
######## Day 1 ###########

dataND1=subset(data,photoperiod!="12")
dataND1=subset(dataND1,sample_day=="1")
dataND1=subset(dataND1,lipid_mass!="NA")
dataND1=subset(dataND1,lipid_mass>="0")
dataND1=subset(dataND1,lipid_mass<="0.2")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedND1=lmer(lipid_mass ~ strain + (1|rep) ,data=dataND1, REML = TRUE)
summary(mixedND1)
plot(mixedND1)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodND1=lmer(lipid_mass ~ (1|rep),data=dataND1, REML = TRUE)
summary(submodND1)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataND1$stdresND1<-as.vector(scale(resid(submodND1)))

ggplot(dataND1,aes(x=sample_day,y=lipid_mass, fill=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Non-Diapause: Strain Comparison of Lipid Mass")+
  ylab("Lipid Mass")

##########NDia############
##Lipid Mass btw  Strain##
######## Day W ###########

dataNDW=subset(data,photoperiod!="12")
dataNDW=subset(dataNDW,sample_day=="W")
dataNDW=subset(dataNDW,lipid_mass!="NA")
dataNDW=subset(dataNDW,lipid_mass>="0")
dataNDW=subset(dataNDW,lipid_mass<="0.2")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedNDW=lmer(lipid_mass ~ strain + (1|rep) ,data=dataNDW, REML = TRUE)
summary(mixedNDW)
plot(mixedNDW)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodNDW=lmer(lipid_mass ~ (1|rep),data=dataNDW, REML = TRUE)
summary(submodNDW)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataNDW$stdresNDW<-as.vector(scale(resid(submodNDW)))


dataND=subset(data,photoperiod!="12")
dataND=subset(dataND,sample_day=="1"|sample_day=="W")
dataND=subset(dataND,lipid_mass!="NA")
dataND=subset(dataND,lipid_mass>="0")
dataND=subset(dataND,lipid_mass<="0.2")
ggplot(dataND,aes(x=sample_day,y=lipid_mass, fill=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Non-Diapause: Strain Comparison of Lipid Mass")+
  ylab("Lipid Mass")
```


```{r}
##########Diap############
##Lipid Mass btw  Strain##
######## Dia Day 1  ######

dataD1=subset(data,photoperiod!="16")
dataD1=subset(dataD1,lipid_mass!="NA")
dataD1=subset(dataD1,sample_day=="1")
dataD1=subset(dataD1,lipid_mass>="0")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedD1=lmer(lipid_mass ~ strain + (1|rep) ,data=dataD1, REML = TRUE)
summary(mixedD1)
plot(mixedD1)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submod=lmer(lipid_mass ~ (1|rep),data=dataD1, REML = TRUE)
summary(submod)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataD1$stdresD1<-as.vector(scale(resid(submod)))

ggplot(dataD1,aes(x=sample_day,y=lipid_mass, fill=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Diapause Day One of 5th Instar: Strain Comparison of Lipid Mass")+
  ylab("Lipid Mass")

##########Diap############
##Lipid Mass btw  Strain##
##### Dia Day 1 & W  #####

dataDW=subset(data,photoperiod!="16")
dataDW=subset(dataDW,lipid_mass!="NA")
dataDW=subset(dataDW,sample_day=="W")
dataDW=subset(dataDW,lipid_mass>="0")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedDW=lmer(lipid_mass ~ strain + (1|rep) ,data=dataDW, REML = TRUE)
summary(mixedDW)
plot(mixedDW)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodDW=lmer(lipid_mass ~ (1|rep),data=dataDW, REML = TRUE)
summary(submod)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataDW$stdresDW<-as.vector(scale(resid(submodDW)))

dataD=subset(data,photoperiod!="16")
dataD=subset(dataD,lipid_mass!="NA")
dataD=subset(dataD,sample_day=="1"|sample_day=="W")
dataD=subset(dataD,lipid_mass>="0")
ggplot(dataD,aes(x=sample_day,y=lipid_mass, fill=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Diapause Wandering Day of 5th Instar: Strain Comparison of Lipid Mass")+
  ylab("Lipid Mass")
```


```{r}
##########Diap############
##Lipid Mass btw  Strain##
####### Dia Day 15 #######

dataD15=subset(data,photoperiod!="16")
dataD15=subset(dataD15,sample_day=="W15")
dataD15=subset(dataD15,lipid_mass!="NA")
dataD15=subset(dataD15,lipid_mass>="0")

#this model attempts to fit the linear mixed effects model with 3 variables; strain, lean mass, and the random effect of rep
mixedD15=lmer(lipid_mass ~ strain + (1|rep) ,data=dataD15, REML = TRUE)
summary(mixedD15)
plot(mixedD15)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodD15=lmer(lipid_mass ~ (1|rep),data=dataD15, REML = TRUE)
summary(submodD15)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataD15$stdresD15<-as.vector(scale(resid(submodD15)))

##########Diap############
##Lipid Mass btw  Strain##
###### Dia Day 20 ########

dataD20=subset(data,photoperiod!="16")
dataD20=subset(dataD20,sample_day=="W20")
dataD20=subset(dataD20,lipid_mass!="NA")
dataD20=subset(dataD20,lipid_mass>="0.0001")
#dataD20=subset(dataD20,lipid_mass<="0.02")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedD20=lmer(lipid_mass ~ strain + (1|rep) ,data=dataD20, REML = TRUE)
summary(mixedD20)
plot(mixedD20)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodD20=lmer(lipid_mass ~ (1|rep),data=dataD20, REML = TRUE)
summary(submodD20)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataD20$stdresD20<-as.vector(scale(resid(submodD20)))

##########Diap############
##Lipid Mass btw  Strain##
###### Dia Day 30 ########

dataD30=subset(data,photoperiod!="16")
dataD30=subset(dataD30,sample_day=="W30")
dataD30=subset(dataD30,lipid_mass!="NA")
#dataD30=subset(dataD30,lipid_mass>="0.0004")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedD30=lmer(lipid_mass ~ strain + (1|rep) ,data=dataD30, REML = TRUE)
summary(mixedD30)
plot(mixedD30)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submod=lmer(lipid_mass ~ (1|rep),data=dataD30, REML = TRUE)
summary(submod)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataD30$stdresD30<-as.vector(scale(resid(submod)))

dataD=subset(data,photoperiod!="16")
dataD=subset(dataD,sample_day=="W15")
dataD=subset(dataD,lipid_mass!="NA")
#dataD=subset(dataD,lipid_mass>="0.0004")
ggplot(dataD,aes(x=sample_day,y=lipid_mass, fill=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Diapause Day 15: Strain Comparison of Lipid Mass")+
  ylab("Lipid Mass")

dataD20=subset(data,sample_day=="W20")
dataD20=subset(dataD20,lipid_mass!="NA")
#dataD=subset(dataD,lipid_mass>="0.0004")
ggplot(dataD20,aes(x=sample_day,y=lipid_mass, fill=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Diapause Day 20: Strain Comparison of Lipid Mass")+
  ylab("Lipid Mass")

dataD=subset(data,photoperiod!="16")
dataD=subset(dataD,sample_day=="W30")
dataD=subset(dataD,lipid_mass!="NA")
#dataD=subset(dataD,lipid_mass>="0.0004")
ggplot(dataD,aes(x=sample_day,y=lipid_mass, fill=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Diapause Day 30: Strain Comparison of Lipid Mass")+
  ylab("Lipid Mass")
```

```{r}
############ BE ##############
##Lipid Mass w/in Strain######
###### Dia Day W v XX ########

dataWv15=subset(data,photoperiod!="16")
dataWv15=subset(dataWv15,strain!="UZ")
dataWv15=subset(dataWv15,sample_day=="W"|sample_day=="W15")
dataWv15=subset(dataWv15,lipid_mass!="NA")
dataWv15=subset(dataWv15,lipid_mass>="0.0004")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedWv15=lmer(lipid_mass ~ sample_day + (1|rep) ,data=dataWv15, REML = TRUE)
summary(mixedWv15)
plot(mixedWv15)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodWv15=lmer(lipid_mass ~ (1|rep),data=dataWv15, REML = TRUE)
summary(submodWv15)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataWv15$stdresWv15<-as.vector(scale(resid(submodWv15)))

ggplot(dataWv15,aes(x=sample_day,y=lipid_mass,fill=sample_day))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("BE Strain: Comparison of Lipid Mass between Wandering day and Day 15")+
  ylab("Lipid Mass")

dataWv20=subset(data,photoperiod!="16")
dataWv20=subset(dataWv20,strain!="UZ")
dataWv20=subset(dataWv20,sample_day=="W"|sample_day=="W20")
dataWv20=subset(dataWv20,lipid_mass!="NA")
dataWv20=subset(dataWv20,lipid_mass>="0.0004")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedWv20=lmer(lipid_mass ~ sample_day + (1|rep) ,data=dataWv20, REML = TRUE)
summary(mixedWv20)
plot(mixedWv20)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodWv20=lmer(lipid_mass ~ (1|rep),data=dataWv20, REML = TRUE)
summary(submodWv20)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataWv20$stdresWv20<-as.vector(scale(resid(submodWv20)))

ggplot(dataWv20,aes(x=sample_day,y=lipid_mass,fill=sample_day))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("BE Strain: Comparison of Lipid Mass between Wandering day and Day 20")+
  ylab("Lipid Mass")

dataWv30=subset(data,photoperiod!="16")
dataWv30=subset(dataWv30,strain!="UZ")
dataWv30=subset(dataWv30,sample_day=="W"|sample_day=="W30")
dataWv30=subset(dataWv30,lipid_mass!="NA")
dataWv30=subset(dataWv30,lipid_mass>="0.0004")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedWv30=lmer(lipid_mass ~ sample_day + (1|rep) ,data=dataWv30, REML = TRUE)
summary(mixedWv30)
plot(mixedWv30)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodWv30=lmer(lipid_mass ~ (1|rep),data=dataWv30, REML = TRUE)
summary(submodWv30)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataWv30$stdresWv30<-as.vector(scale(resid(submodWv30)))

ggplot(dataWv30,aes(x=sample_day,y=lipid_mass,fill=sample_day))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("BE Strain: Comparison of Lipid Mass between Wandering day and Day 30")+
  ylab("Lipid Mass")
```
```{r}
############ UZ ##############
##Lipid Mass w/in Strain######
###### Dia Day W v 30 ########

datauWv15=subset(data,photoperiod!="16")
datauWv15=subset(datauWv15,strain!="BE")
datauWv15=subset(datauWv15,sample_day=="W"|sample_day=="W15")
datauWv15=subset(datauWv15,lipid_mass!="NA")
datauWv15=subset(datauWv15,lipid_mass>="0.0004")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixeduWv15=lmer(lipid_mass ~ sample_day + (1|rep) ,data=datauWv15, REML = TRUE)
summary(mixeduWv15)
plot(mixeduWv15)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submoduWv15=lmer(lipid_mass ~ (1|rep),data=datauWv15, REML = TRUE)
summary(submoduWv15)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
datauWv15$stdresuWv15<-as.vector(scale(resid(submoduWv15)))

ggplot(datauWv15,aes(x=sample_day,y=lipid_mass,fill=sample_day))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("UZ Strain: Comparison of Lipid Mass between Wandering day and Day 15")+
  ylab("Lipid Mass")

datauWv20=subset(data,photoperiod!="16")
datauWv20=subset(datauWv20,strain!="BE")
datauWv20=subset(datauWv20,sample_day=="W"|sample_day=="W20")
datauWv20=subset(datauWv20,lipid_mass!="NA")
datauWv20=subset(datauWv20,lipid_mass>="0.0004")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixeduWv20=lmer(lipid_mass ~ sample_day + (1|rep) ,data=datauWv20, REML = TRUE)
summary(mixeduWv20)
plot(mixeduWv20)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submoduWv20=lmer(lipid_mass ~ (1|rep),data=datauWv20, REML = TRUE)
summary(submoduWv20)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
datauWv20$stdresuWv20<-as.vector(scale(resid(submoduWv20)))

ggplot(datauWv20,aes(x=sample_day,y=lipid_mass,fill=sample_day))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("UZ Strain: Comparison of Lipid Mass between Wandering day and Day 20")+
  ylab("Lipid Mass")

datauWv30=subset(data,photoperiod!="16")
datauWv30=subset(datauWv30,strain!="BE")
datauWv30=subset(datauWv30,sample_day=="W"|sample_day=="W30")
datauWv30=subset(datauWv30,lipid_mass!="NA")
datauWv30=subset(datauWv30,lipid_mass>="0.0004")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixeduWv30=lmer(lipid_mass ~ sample_day + (1|rep) ,data=datauWv30, REML = TRUE)
summary(mixeduWv30)
plot(mixeduWv30)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submoduWv30=lmer(lipid_mass ~ (1|rep),data=datauWv30, REML = TRUE)
summary(submoduWv30)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
datauWv30$stdresuWv30<-as.vector(scale(resid(submoduWv30)))

ggplot(datauWv30,aes(x=sample_day,y=lipid_mass,fill=sample_day))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("UZ Strain: Comparison of Lipid Mass between Wandering day and Day 30")+
  ylab("Lipid Mass")

```

```{r}
########## UZ ############
##Lipid Mass w/in Strain##
######## Day 1 ###########

##Mixed model with 'rep' as a random factor
dataUZ1=subset(data,strain!="BE")
dataUZ1=subset(dataUZ1,sample_day=="1")
dataUZ1=subset(dataUZ1,lipid_mass>="0")
dataUZ1=subset(dataUZ1,lipid_mass<="0.02")
dataUZ1=subset(dataUZ1,lipid_mass!="NA")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedUZ1=lmer(lipid_mass ~ photoperiod + (1|rep) ,data=dataUZ1, REML = TRUE)
summary(mixedUZ1)
plot(mixedUZ1)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodUZ1=lmer(lipid_mass ~ (1|rep),data=dataUZ1, REML = TRUE)
summary(submodUZ1)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataUZ1$stdresUZ1<-as.vector(scale(resid(submodUZ1)))

########## UZ ############
##Lipid Mass w/in Strain##
######## Day W ###########

##Mixed model with 'rep' as a random factor
dataUZW=subset(data,strain!="BE")
dataUZW=subset(dataUZW,sample_day=="W")
dataUZW=subset(dataUZW,lipid_mass>="0")
dataUZW=subset(dataUZW,lipid_mass<="0.02")
dataUZW=subset(dataUZW,lipid_mass!="NA")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedUZW=lmer(lipid_mass ~ photoperiod + (1|rep) ,data=dataUZW, REML = TRUE)
summary(mixedUZW)
plot(mixedUZW)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodUZW=lmer(lipid_mass ~ (1|rep),data=dataUZW, REML = TRUE)
summary(submodUZW)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataUZW$stdresUZW<-as.vector(scale(resid(submodUZW)))

dataUZ=subset(data,strain!="BE")
dataUZ=subset(dataUZ,sample_day=="1"|sample_day=="W")
dataUZ=subset(dataUZ,lipid_mass>="0")
dataUZ=subset(dataUZ,lipid_mass<="0.02")
dataUZ=subset(dataUZ,lipid_mass!="NA")
ggplot(dataUZ,aes(x=sample_day,y=lipid_mass,fill=treat))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("UZ Strain: Comparison of Treatment")+
  ylab("Lipid Mass")


########## BE ############
##Lipid Mass w/in Strain##
######## Day 1 ###########

##Mixed model with 'rep' as a random factor
dataBE1=subset(data,strain!="UZ")
dataBE1=subset(dataBE1,sample_day=="1")
dataBE1=subset(dataBE1,lipid_mass>="0")
dataBE1=subset(dataBE1,lipid_mass!="NA")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedBE1=lmer(lipid_mass ~ photoperiod + (1|rep) ,data=dataBE1, REML = TRUE)
summary(mixedBE1)
plot(mixedBE1)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodBE1=lmer(lipid_mass ~ (1|rep),data=dataBE1, REML = TRUE)
summary(submodBE1)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataBE1$stdresBE1<-as.vector(scale(resid(submodBE1)))

########## BE ############
##Lipid Mass w/in Strain##
######## Day W ###########

##Mixed model with 'rep' as a random factor
dataBEW=subset(data,strain!="UZ")
dataBEW=subset(dataBEW,sample_day=="W")
dataBEW=subset(dataBEW,lipid_mass>="0")
dataBEW=subset(dataBEW,lipid_mass!="NA")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedBEW=lmer(lipid_mass ~ photoperiod + (1|rep) ,data=dataBEW, REML = TRUE)
summary(mixedBEW)
plot(mixedBEW)
##The following model removes photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submodBEW=lmer(lipid_mass ~ (1|rep),data=dataBEW, REML = TRUE)
summary(submodBEW)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataBEW$stdresBEW<-as.vector(scale(resid(submodBEW)))

dataBE=subset(data,strain!="UZ")
dataBE=subset(dataBE,sample_day=="1"|sample_day=="W")
dataBE=subset(dataBE,lipid_mass>="0")
dataBE=subset(dataBE,lipid_mass!="NA")
ggplot(dataBE,aes(x=sample_day,y=lipid_mass,fill=treat))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("BE Strain: Comparison of Treatment")+
  ylab("Lipid Mass")
```

```{r}
##########################
##Lipid Mass INTRX Strain#
######## Day 1 ###########

dataI1=subset(data,lipid_mass!="NA")
dataI1=subset(dataI1,sample_day=="1")
dataI1=subset(dataI1,lipid_mass>="0")
dataI1=subset(dataI1,lipid_mass<="0.02")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedI1=lmer(lipid_mass ~ photoperiod*strain+(1|rep),data=dataI1, REML = TRUE)
summary(mixedI1)
plot(mixedI1)
##The following model removes strain and photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submod=lmer(lipid_mass ~ (1|rep),data=dataI1, REML = TRUE)
summary(submod)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataI1$stdresI1<-as.vector(scale(resid(submod)))

ggplot(dataI1,aes(x=strain,y=lipid_mass, group=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Interaction Day 1: Effect of Photoperiod x  Strain")+
  ylab("Lipid Mass")

##########################
##Lipid Mass INTRX Strain#
######## Day W ###########

dataIW=subset(data,lipid_mass!="NA")
dataIW=subset(dataIW,sample_day=="W")
dataIW=subset(dataIW,lipid_mass>="0")
dataIW=subset(dataIW,lipid_mass<="0.02")

#this model attempts to fit the linear mixed effects model with 3 variables; photoperiod, lean mass, and the random effect of rep
mixedIW=lmer(lipid_mass ~ photoperiod*strain+(1|rep),data=dataIW, REML = TRUE)
summary(mixedIW)
plot(mixedIW)
##The following model removes strain and photoperiod as factors to determine the effect of lean mass and Rep on lipid mass
submod=lmer(lipid_mass ~ (1|rep),data=dataIW, REML = TRUE)
summary(submod)

## Standard Residuals -  Adding stdres to df and checking for regularity of distribution within +/-2 standard deviations  
dataIW$stdresIW<-as.vector(scale(resid(submod)))

ggplot(dataIW,aes(x=strain,y=lipid_mass, group=strain))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("Interaction Wandering Day: Effect of Photoperiod x  Strain")+
  ylab("Lipid Mass")
````